name: Build and push an Adelie Linux container image
on:
  schedule:
    - cron: '53 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: login to container registry
        run: podman login -u "$QUAY_USER" -p "$QUAY_TOKEN" quay.io
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

      - name: install ripgrep
        run: apt --no-install-recommends install ripgrep

      - name: do the thing
        run: ./mk.sh --push
